### ISSUE TITLE
[Refactoring] 타입 구조 리팩토링 

### ISSUE THREAD

**Issue by yonghyeun** [dogandme/frontend#523]
### cross-import

<img width="913" alt="스크린샷 2024-12-09 오후 9 34 29" src="https://github.com/user-attachments/assets/5ac6237a-e10b-4320-adbd-355c8832de00">

### 데이터 타입을 어디다가 둘건지?

- `*/도메인/api/type.ts`: 여러 쿼리문에서 사용하는 타입들
- `*/도메인/api/use*.ts`: 해당 쿼리문에서만 사용하는 타입들

**Comment by yonghyeun** [comment]
# 우리 코드에서 존재하는 타입 잘못된 사용 1 

```tsx
interface LatLng {
  lat: number;
  lng: number;
}

interface Bounds {
  southWestLat: number;
  southWestLng: number;
  northEastLat: number;
  northEastLng: number;
}
```

다음과 같이 여러 세그먼트에서 사용되는 공통된 타입들이 존재합니다. 

처음에는 세그먼트 상관 없이 먼저 선언된 곳에서 import 해왔으나 그러면 안된단걸 깨닫고 리팩토링 시 만지자며 사용되는 각 파일마다 사용되는 interface 들을 생성해두었습니다. 

FSD 공식문서에서는 여러 세그먼트에서 공유해야 할 타입을 관리하는 두 가지 방법을 소개하는데

하나는 타입이 단순하다면 한 번 더 작성해주는 것과  

`slice/segement/@x/` 와 같은 크로스 폴더를 만들어 관리하는 편을 소개 합니다. 

현재 이렇게 cross import 되는 타입들의 예시를 살펴보면 아마 대표적으로 이런 것들일 것입니다. 

- lat , lng 
- regions 
- bounds 
- profile 정보 (nickname , .... pet)

저는 크로스 폴더를 만들어도 고민이 되는 부분이 예를 들어 `lat , lng` 같은 타입을 크로스 폴더에 만들어 관리한다고 해도 

그럼 결국 어떤 도메인에 만들어야 할지? 가 고민입니다. 

타입 자체의 의미로 따지면 `map` 에 있어야만 할 거 같지만 해당 타입이 클라이언트 단에서 생성되는 곳은 회원가입이기에  `features/auth` 파트이고 .. 

이래서 공식문서에서 그냥 api 들을 모두 shared 에 때려박아둔 것일까요

**Comment by aken-you** [comment]
현재 [import 구조](https://feature-sliced.design/kr/docs/reference/layers#import-rule-on-layers)를 어기고 있는 곳이 몇 군데 있습니다.
대부분 다른 도메인의 데이터 type을 참조해야 하는 경우인데요.

이런 경우 [공식문서](https://feature-sliced.design/kr/docs/guides/examples/types)에서 총 3가지 방법을 제시합니다.

1. 타입 매개변수화
2. shared/api/도메인.ts
3. cross import

1번 방법은 참조해야 하는 타입과 밀접하게 관련이 있어 적절하지 않다고 생각합니다.

2번 방법은 하나의 도메인 파일 안에 api 요청 커스텀 훅을 넣어야 하는데요.
하나의 파일로 관리하기에는 유지보수하기 좋지 않을 것 같습니다.
그래서 `shared/api/도메인/useGet*` 이런 식으로 관리해야 관리하기 편할 것 같습니다.

3번 방법은 현재 상황에서 가장 빨리 적용할 수 있는 방법이라고 생각합니다.
현재 프로젝트의 구조를 지키면서 `@x` 폴더만 추가하여 리팩토링 하면 됩니다.
하지만 cross-import를 최소화하기 위해 [`@x` 폴더는 오직 entities 레이어에서만 사용](https://feature-sliced.design/kr/docs/reference/public-api#public-api-for-cross-imports)하라고 하더라구요.

개인적으로, 2번과 3번 방법 중 하나로 리팩토링하는 것이 좋아보입니다.

그리고 여러 곳에서 많이 쓰이는 타입 같은 경우 어떤 방법을 선택해도 고민되는 부분입니다.
이 타입이 있어야 할 도메인을 분명하게 정해야 하는 게 핵심 같습니다.

**Comment by yonghyeun** [comment]
저도 동의합니다 

저희의 서버 리스폰스 DTO 가 대부분 비슷한 데이터들을 다루고 있기 때문에 걱정했던 것 만큼 대규모 공사가 아닐 수도 있겠다는 생각이 들기도 하네요 

저는 개인적으로 3번이 좀 더 마음에 듭니다.

저희가 entities 는 주로 get(r) 에 대한 요청으로 , features 는 나머지 c,u,d 에 해당하는 api 요청들로 약속하고 만들어놨는데요 

프로젝트에서 DTO 들에 해당하는 타입들은 CRUD 중 어떤 것인지와는 크게 상관 없이 독립적으로 존재해야 한다고 생각하기 때문입니다.

**Comment by yonghyeun** [comment]
또 지금 문득 드는 생각이 저희가 가장 많이 사용하는 타입인 `Marking` 의 경우  

```tsx
export interface Marking {
  markingId: number;
  region: string;
  content: string;
  isVisible: MarkingVisibilityKey;
  regDt: string;
  previewImage: string;
  userId: number;
  nickName: string;
  isOwner: boolean;
  isTempSaved: boolean;
  lat: number;
  lng: number;
  address: Address;
  countData: Count;
  pet: Pet;
  images: Image[];
}
```

해당 타입을 이루고 있는 타입들의 도메인을 굳이 따지자면 pet, region , userId , nickname .. 등등은 profile 혹은 auth 도메인에서 생성된 타입들인데 

마킹 슬라이스에 있는 것이 다른 슬라이스에 있는 타입을 호다닥 조합해서 사용해도 괜찮을까요 ? 이 방법은 또 어떻게 해야 할지 고민이군요

**Comment by yonghyeun** [comment]
몇몇 부분은 타입뿐 아니라 구조부터가 잘못된 부분들이 존재합니다. 예를 들어 현재  `features/auth/ui` 에 존재하는 `dashboard.tsx` 파일이 그런데요 

```tsx
import { useChangePetInfoModal } from "@/features/setting/hooks/useChangePetInfoModal";
import { PetInfo } from "@/entities/profile/api";
import { EditIcon } from "@/shared/ui/icon";

export const ProfileEditButton = ({ pet }: { pet: PetInfo }) => {
  const handleOpen = useChangePetInfoModal(pet);

  return (
    <button
      className="w-6 h-6"
      aria-label="프로필 설정 수정 하기 버튼"
      onClick={handleOpen}
    >
      <EditIcon />
    </button>
  );
};
```

를 살펴보면 `auth` 에 존재하는 컴포넌트가 `setting` 도메인에서 훅을 , `profile` 에서 타입을 가져옵니다. 

크갹

**Comment by aken-you** [comment]
## 리팩토링

### cross-import

<img width="913" alt="스크린샷 2024-12-09 오후 9 34 29" src="https://github.com/user-attachments/assets/5ac6237a-e10b-4320-adbd-355c8832de00">

### 데이터 타입을 어디다가 둘건지?

- `*/도메인/api/type.ts`: 여러 쿼리문에서 사용하는 타입들
- `*/도메인/api/use*.ts`: 해당 쿼리문에서만 사용하는 타입들

**Comment by aken-you** [comment]
## request, response, props 타입

- response와 request 타입 선언하기
- props 타입 선언하기

## 서버 api에서 받은 데이터를 사용하는 Props 타입

- 컴포넌트의 props가 데이터 타입과 밀접하게 관련되어 있을 경우, 데이터 타입 + 유틸리티 타입으로 설정
- 컴포넌트의 props가 여러 데이터 타입과 관련되어 있을 경우, 원시 타입
- 스토어의 데이터가 서버 데이터에 종속 된 경우에는 서버에서 가져오는걸로 

## `layer/slice/types`

여러 곳에서 사용되는 타입들은 도메인 밑에 types 폴더에 정의합니다.

- `server.ts`: 서버로부터 오는 데이터 타입 선언
- `client.ts`:  클라이언트 쪽에서 사용하는 데이터 타입 선언
